## Vetores

In [2]:
def vector_add(v, w):
    '''
        Soma de vetores correspondentes
    '''
    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [3]:
def vector_diff(v, w):
    '''
        Subtraindo vetores correspondentes
    '''
    return [v_i - w_i for v_i, w_i in zip(v, w)]

In [4]:
v = [1, 2, 3]
w = [1, 2, 3]

add = vector_add(v, w)
diff = vector_diff(v, w)
print(add)
print(diff)

[2, 4, 6]
[0, 0, 0]


# Usando Numpy
## Multiplicação de matrizes 

In [41]:
import numpy as np

np.dot(v, w)

14

Criando um Array

In [59]:
x = np.array([[3, 4], [2, 5]])

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

x, a, b

(array([[3, 4],
        [2, 5]]), array([1, 2, 3]), array([2, 2, 2]))

Mostrando shape do array

In [64]:
x.shape, a.shape, b.shape

((2, 2), (3,), (3,))

Calculanto a matriz transposta

In [35]:
x.T

array([[3, 2],
       [4, 5]])

Multiplicando elemento a elemento

In [72]:
x * x, np.dot(x, x)

(array([[ 9, 16],
        [ 4, 25]]), array([[17, 32],
        [16, 33]]))

In [70]:
x.dot(x)


array([[17, 32],
       [16, 33]])

Calculando a matriz inversa

In [71]:
np.linalg.inv(x)

array([[ 0.71428571, -0.57142857],
       [-0.28571429,  0.42857143]])